# Docker
# Build and Push Spring Boot Docker Image

trigger:
  - main

# Build Number format:
name: 3.0.$(Date:yyyyMMdd).$(Rev:r)

resources:
  - repo: self

variables:
  imageName: deposit-dashboard

stages:
  - stage: Build
    displayName: Build and Push Image

    jobs:
      - job: Build

        # Change this to your self-hosted pool if applicable
        pool:
          vmImage: ubuntu-latest
          # name: MySelfHostedPool

        steps:
          - checkout: self

          - task: DownloadSecureFile@1
            name: securityFile
            inputs:
              secureFile: certs.tar.gz

          - script: |
              cp "$(securityFile.secureFilePath)" "$(Build.SourcesDirectory)/certs.tar.gz"
            displayName: Prepare security files

          - script: |
              VERSION=$(bash gradlew properties -q | grep "^version:" | awk '{print $2}')
              echo "Project Version: $VERSION"
              echo "##vso[task.setvariable variable=tag]$VERSION"
            displayName: Get Project Version

          - script: |
              echo "Build Number: $(Build.BuildNumber)"
              echo "Image Tag: $(tag)"
            displayName: Show Build Information

          - script: |
              echo "$(REGISTRY_PASSWORD)" | docker login \
                $(REGISTRY_SERVER) \
                --username "$(REGISTRY_USERNAME)" \
                --password-stdin
            displayName: Login to Registry

          - script: |
              docker build \
                -t $(imageName):$(tag) \
                -f "$(Build.SourcesDirectory)/Dockerfile" \
                "$(Build.SourcesDirectory)"
            displayName: Build Image

          - script: |
              docker tag \
                $(imageName):$(tag) \
                $(REGISTRY_SERVER)/$(imageName):$(tag)

              docker tag \
                $(imageName):$(tag) \
                $(REGISTRY_SERVER)/$(imageName):latest
            displayName: Tag Image

          - script: |
              docker push $(REGISTRY_SERVER)/$(imageName):$(tag)
              docker push $(REGISTRY_SERVER)/$(imageName):latest
            displayName: Push Image

          - script: |
              docker logout $(REGISTRY_SERVER)
            displayName: Logout
            condition: always()
