# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: $(Build.BuildId)
  imageName: deposit-dashboard

stages:
  - stage: Build
    displayName: Build and Push Image

    jobs:
      - job: Build

        # Change this to your self-hosted pool if applicable
        pool:
          vmImage: ubuntu-latest
          # name: MySelfHostedPool

        steps:
          - checkout: self

          - task: DownloadSecureFile@1
            name: securityFile
            inputs:
              secureFile: certs.tar.gz

          - script: |
              cp "$(securityFile.secureFilePath)" "$(Build.SourcesDirectory)/certs.tar.gz"
            displayName: Prepare security files

          - script: |
              echo "$(REGISTRY_PASSWORD)" | docker login \
                $(REGISTRY_SERVER) \
                --username "$(REGISTRY_USERNAME)" \
                --password-stdin
            displayName: Login to Registry

          - script: |
              docker build \
                -t $(imageName):$(tag) \
                -f "$(Build.SourcesDirectory)/Dockerfile" \
                "$(Build.SourcesDirectory)"
            displayName: Build Image

          - script: |
              docker tag \
                $(imageName):$(tag) \
                $(REGISTRY_SERVER)/$(imageName):$(tag)

              docker tag \
                $(imageName):$(tag) \
                $(REGISTRY_SERVER)/$(imageName):latest
            displayName: Tag Image

          - script: |
              docker push $(REGISTRY_SERVER)/$(imageName):$(tag)
              docker push $(REGISTRY_SERVER)/$(imageName):latest
            displayName: Push Image

          - script: |
              docker logout $(REGISTRY_SERVER)
            displayName: Logout
            condition: always()
