#!/bin/bash

version=2.1.0

CMD=$1
INSTALL_PATH=`pwd`
image_name=deposit-dashboard
docker_name=dashboard
docker_network=deposit_dashboard_network_x

select_container_engine() {
    if command -v podman &> /dev/null; then
        echo "podman"
    elif command -v docker &> /dev/null; then
        echo "docker"
    else
        echo "Error: Neither podman nor docker is installed." >&2
        exit 1
    fi
}

CONTAINER_ENGINE=$(select_container_engine)

select_container_compose() {
    if command -v podman &> /dev/null; then
        echo "podman-compose"
    elif command -v docker &> /dev/null; then
        echo "docker compose"
    else
        echo "Error: Neither podman nor docker is installed." >&2
        exit 1
    fi
}

CONTAINER_COMPOSE=$(select_container_compose)


case $CMD in
    build)
    eval "$CONTAINER_ENGINE build --no-cache -f Dockerfile --tag ${image_name} ."
    ;;

    up)
    eval "$CONTAINER_COMPOSE -f $INSTALL_PATH/docker-compose.yml --env-file $INSTALL_PATH/.env up --detach dashboard"
    ;;

    down)
    eval "$CONTAINER_COMPOSE -f $INSTALL_PATH/docker-compose.yml down"
    ;;

    logs)
    podman ps --format '{{.ID}} {{.Names}}' | awk 'NR==FNR{map[$1]=$2;next} {cid=$1; $1=map[cid]; print}' - <(podman-compose logs -f)
    ;;

    exec)
    eval "$CONTAINER_ENGINE exec -it ${docker_name} bash"
    ;;
    push)
    docker push 
    ;;

    *)
    echo "dev: Deposit Dashboard"
    echo "Usage:"
    echo "dev build"
    echo "    build the docker image, all the service in one container."
    echo "dev up"
    echo "    start the docker container"
    echo "dev down"
    echo "    stop the docker container"
    echo "dev logs"
    echo "    print the logs of the docker container"
    echo "dev push"
    echo "    push the current image to docker hub"
esac
